source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

platform :ios, '7.0'

target 'MXParallaxHeader_Example', :exclusive => true do
  pod "MXParallaxHeader", :path => "../"
end

target 'MXParallaxHeader_Tests', :exclusive => true do
  pod "MXParallaxHeader", :path => "../"

  
end
