source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MXParallaxHeader_Example', :exclusive => true do
  pod "MXParallaxHeader", :path => "../"
  pod 'M13ProgressSuite', '~> 1.2.7'
end

target 'MXParallaxHeader_Tests', :exclusive => true do
  pod "MXParallaxHeader", :path => "../"

  
end
